version: "3.1"
services:
    backend:
        image: webdevops/php-nginx:7.2
        container_name: ${CONTAINER_PREFIX}_backend
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        volumes:
            - ../:/var/www/html
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/html${DOCUMENT_ROOT_DIRECTORY}
        working_dir: /var/www/html
    postgres:
        image: sameersbn/postgresql:10
        container_name: ${CONTAINER_PREFIX}_postgres
        environment:
            - PG_PASSWORD=${POSTGRES_ROOT_PASSWORD}
            - DB_USER=${POSTGRES_USER}
            - DB_PASS=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DATABASES}
        volumes:
            - ./persistence/postgres:/var/lib/postgresql/data
            # For external volume:
            #- postgres_persistence:/var/lib/postgresql/data
    pga:
        image: dpage/pgadmin4
        container_name: ${CONTAINER_PREFIX}_pga
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
            - PGADMIN_ENABLE_TLS=
        ports:
            - "${PGA_PORT}:80"
        volumes:
            - ./persistence/pgadmin/:/var/lib/pgadmin
    redis:
        image: redis
        container_name: ${CONTAINER_PREFIX}_redis
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./persistence/redis:/data

# For external volume:
#volumes:
#    postgres_persistence:
#        external: true


